---

- hosts: all
  gather_facts: false
  tasks:
    - name: 'ensure python2 is present'
      raw: 'which python || apt-get install -y python python-simplejson'
      changed_when: false

- hosts: all
  vars:
    nginx_dhparam_length: 256

    nginx_includes:
      - log_formats
      - proxy_params
      - realip

    nginx_http_includes:
      - log_formats
      - proxy_params
      - realip

    nginx_real_ip_from:
      - 10.0.0.0/8
      - 192.168.0.0/16

    nginx_servers:
      - name: molecule
        server_name: _

    frontlb_servers:
      - name: example.com
        server_name: example.com
        lb_method: 'least_conn'
        upstreams:
          - address : '10.1.109.5'
          - address : '10.1.109.6'
          - address : '10.1.109.7'

  roles:
    - role: nginx
