---
# vi: set ft=ansible :

- name: Ensure directory for certificates exists
  file:
    path: '{{ nginx_tls_path }}/{{ item.server_name }}'
    state: directory

- name: Copy TLS certificate
  copy:
    content: '{{ item.tls.cert }}'
    dest: '{{ nginx_tls_path }}/{{ item.server_name }}/fullchain.pem'
  notify: nginx reload
  when: >
    item.tls is defined and
    not (item.certbot is defined and item.certbot)

- name: Copy TLS key
  copy:
    content: '{{ item.tls.key }}'
    dest: '{{ nginx_tls_path }}/{{ item.server_name }}/privkey.pem'
  notify: nginx reload
  when: >
    item.tls is defined and
    not (item.certbot is defined and item.certbot)

- name: Install server config
  template:
    src: 'library/templates/nginx.frontlb.j2'
    dest: '{{ nginx_etc_path }}/conf.d/frontlb.conf'
    mode: '0640'
    owner: 'root'
    group: '{{ nginx_user }}'
    backup: 'yes'
  notify: nginx reload

- name: Ensure directory for challenges exists
  file:
    path: '{{ nginx_acme_path }}'
    state: 'directory'
  tags: nginx_acme

- name: Copy ACME challenge
  copy:
    content: '{{ acme }}'
    dest: '{{ nginx_acme_path }}/{{ acme | splitext | first }}'
  with_items: '{{ item.acme_signature | default([]) }}'
  loop_control:
    loop_var: acme
  tags: nginx_acme

- name: Copy htpasswd file
  htpasswd:
    path: '{{ nginx_etc_path }}/htpasswd_{{ item.name }}'
    name: '{{ user.name }}'
    password: '{{ user.pass }}'
    owner: 'root'
    group: 'www-data'
    mode: '0644'
  with_items: '{{ item.auth | default([]) }}'
  loop_control:
    loop_var: user
