---
# vi: set ft=ansible :

- name: Ensure repository is present
  apt_repository:
    repo: '{{ item.source }}'
    state: present
  with_items: '{{ depends_repos | default([]) }}'

- name: Ensure required packages are present
  apt:
    package: '{{ item }}'
    state: present
  with_items: '{{ depends | default([]) }}'

- name: Ensure nginx repository key is present
  apt_key:
    url: '{{ nginx_repo.key }}'
    state: present
    validate_certs: no
  when: nginx_repo.key is defined

- name: Ensure nginx repository key (id) is present
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '{{ nginx_repo.key_id }}'    
    state: present
  when: nginx_repo.key_id is defined

- name: Ensure nginx repository is present
  apt_repository:
    repo: '{{ nginx_repo.source }}'
    state: present

- name: Ensure python-passlib is present
  apt:
    package: 'python-passlib'
    state: 'present'

- name: Ensure nginx is installed
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{ nginx_packages }}'

- name: Ensure nginx is running and enabled
  service:
    name: 'nginx'
    state: 'started'
    enabled: yes
