---

- include: 'setup.yml'

- name: "{{ title }}: ensure SSL directory exists"
  file:
    path: "{{ nginx_ssl_path }}"
    state: directory

- stat:
    path: "/etc/ssl/certs/dhparam.pem"
  register: dhparam

- name: "{{ title }}: generate Diffie-Hellman group"
  command: "openssl dhparam -out /etc/ssl/certs/dhparam.pem {{ nginx_ssl_dhparam_length }}"
  when: |
    dhparam.stat.exists == False
    and vault_ssl is defined

- include: 'configuration.yml'
  with_items: '{{ nginx_servers }}'
  tags: config
