---
# vi: set ft=ansible :

- name: 'set os dependent variables'
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - '{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml'
      - '{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml'
      - '{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_distribution|lower }}.yml'
      - '{{ ansible_os_family|lower }}.yml'
      paths:
        - '../vars'

- include: 'install.yml'
  static: yes
  when: not nginx_skip_install

- name: '{{ title }}: generate Diffie-Hellman group'
  command: 'openssl dhparam -out {{ nginx_dhparam_path }} {{ nginx_dhparam_length }}'
  args:
    creates: '{{ nginx_dhparam_path }}'
  tags: nginx_config

- name: 'deploy config includes'
  template:
    src: 'library/templates/nginx.{{ item }}.j2'
    dest: '{{ nginx_etc_path }}/{{ item }}'
    mode: '0640'
    owner: 'root'
    group: '{{ nginx_user }}'
    backup: 'yes'
  tags: nginx_config
  with_items: '{{ nginx_includes | default([]) }}'
  notify: nginx reload

- name: 'deploy {{ nginx_etc_path }}/nginx.conf'
  template:
    src: 'library/templates/_nginx.conf.j2'
    dest: '{{ nginx_etc_path }}/nginx.conf'
    mode: '0640'
    owner: 'root'
    group: '{{ nginx_user }}'
    backup: 'yes'
  tags: nginx_config
  notify: nginx reload

- name: 'deploy nginx vhost configs'
  include: 'configure.yml'
  with_items: '{{ nginx_servers | default([]) }}'
  tags: nginx_config

- name: 'deploy nginx slb config'
  include: 'configure_frontlb.yml'
  with_items: '{{ frontlb_servers | default([]) }}'
  tags: nginx_config
