---
# vi: set ft=ansible :

- include: 'setup-Debian.yml'

- name: '{{ title }}: check if Diffie-Hellman group file exists'
  stat:
    path: '{{ nginx_ssl_dhparam_path }}'
  register: dhparam

- name: '{{ title }}: generate Diffie-Hellman group'
  command: 'openssl dhparam -out {{ nginx_ssl_dhparam_path }} {{ nginx_ssl_dhparam_length }}'
  when: dhparam.stat.exists == False

- name: '{{ title }}: install config includes'
  template:
    src: 'library/templates/nginx.{{ item }}.j2'
    dest: '{{ nginx_etc_path }}/{{ item }}'
    mode: '0640'
    owner: 'root'
    group: '{{ nginx_user }}'
    backup: 'yes'
  tags: nginx_config
  with_items: '{{ nginx_includes | default([]) }}'
  notify: nginx reload

- include: 'configuration.yml'
  with_items: '{{ nginx_servers }}'
  tags: nginx_config
