---
# vi: set ft=ansible :

- name: "{{ title }}: add PPA repository"
  apt_repository:
    repo: 'ppa:nginx/stable'
    state: present

- name: "{{ title }}: install the server"
  apt:
    package: nginx
    state: latest
    update_cache: yes

- name: '{{ title }}: ensure python-passlib is present'
  apt:
    package: 'python-passlib'
    state: 'latest'
    update_cache: 'yes'

- name: "{{ title }}: ensure service started and enabled"
  service:
    name: nginx
    enabled: yes
    state: started

- name: '{{ title }}: ensure the default vhost is disabled'
  file:
    path: '/etc/nginx/conf.d/default'
    state: 'absent'
  notify: nginx reload

- name: '{{ title }}: ensure the default vhost is disabled'
  file:
    path: '/etc/nginx/nabled/default'
    state: 'absent'
  notify: nginx reload
