---
# vi: set ft=ansible :

- name: '{{ title }}: ensure required packages are present'
  apt:
    package: '{{ item }}'
    state: present
  with_items:
    - python-urllib3
    - python-ndg-httpsclient

- name: '{{ title }}: ensure repository key is present'
  apt_key:
    url: 'https://nginx.org/keys/nginx_signing.key'
    state: present
    validate_certs: no
  when: ansible_distribution == 'Debian'

- name: '{{ title }}: ensure repository is present'
  apt_repository:
    repo: 'ppa:nginx/stable'
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: '{{ title }}: ensure repository is present'
  apt_repository:
    repo: 'deb http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx'
    state: present
  when: ansible_distribution == 'Debian'

- name: "{{ title }}: install the server"
  apt:
    package: nginx
    state: latest
    update_cache: yes

- name: '{{ title }}: ensure python-passlib is present'
  apt:
    package: 'python-passlib'
    state: 'latest'
    update_cache: 'yes'

- name: "{{ title }}: ensure service started and enabled"
  service:
    name: nginx
    enabled: yes
    state: started

- name: '{{ title }}: ensure the default vhost is disabled'
  file:
    path: '/etc/nginx/conf.d/default'
    state: 'absent'
  notify: nginx reload

- name: '{{ title }}: ensure the default vhost is disabled'
  file:
    path: '/etc/nginx/nabled/default'
    state: 'absent'
  notify: nginx reload
