---
# vi: set ft=ansible :

- name: nginx reload
  service:
    name: nginx
    state: reloaded

- name: nginx restart
  command: nginx -t
  notify: nginx restart_

- name: nginx restart_
  service:
    name: nginx
    state: restarted
