---
# vi: set ft=ansible :

- name: nginx reload
  command: nginx -t
  notify: nginx reload_

- name: nginx restart
  service: name=nginx state=restarted
  notify: nginx restart_

- name: nginx reload_
  service: name=nginx state=reloaded

- name: nginx restart_
  service: name=nginx state=restarted
  notify: nginx test
